name: mint_by_iw
description: Flutter SDk for Mint by Investwell .
version: 0.0.1
#authors: Laxmi kant <laxmikant.pal@investwellonline.com>
homepage: https://github.com/laxmikant86/flutter_mint_sdk
issue_tracker: https://github.com/laxmikant86/flutter_mint_sdk/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  http_interceptor: ^1.0.2
  pretty_http_logger: ^0.2.2
  fluttertoast: ^8.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.example.mintsamplle
        pluginClass: FlutterMintPlugin
